### ISSUE TITLE
Add credits and make your changes clearer

### ISSUE THREAD

**Issue by seriousfreezing** [Tminec/faster-quality-modpack#1]
This issue is about your “Bedrock Edition: Renew” modpack. I am the creator of the base you used to make your modpack and I ask you to leave the credits in your description (mine and my team's) and to make it clearer what the differences are between your modpack and mine.

**Comment by seriousfreezing** [comment]
Please remove all artwork from my modpack. I'll go into more detail in my repository as to why, but you won't be allowed to use the artwork

**Comment by Tminec** [comment]
> This issue is about your “Bedrock Edition: Renew” modpack. I am the creator of the base you used to make your modpack and I ask you to leave the credits in your description (mine and my team's) and to make it clearer what the differences are between your modpack and mine.

Yo sorry about that! I am gonna give you the credits :D (sorry I forget)

**Comment by seriousfreezing** [comment]
Thanks, I'll be waiting for you to remove the artwork from the fancymenu/assets/icons folder. You can use the other artwork as you like, as it's not by the same artist.

**Comment by Tminec** [comment]
I will remove them as soon as I can but I am a bit busy these days so I will do it soon

**Comment by Tminec** [comment]
> Please remove all artwork from my modpack. I'll go into more detail in my repository as to why, but you won't be allowed to use the artwork

The camera icon, marketplace and other bedrock rips was your artwork right?

**Comment by Tminec** [comment]
Also tbh, when me and SoftwareDevKit was doing the first version, we didn't even know about your modpack, after I finished the first version and added FancyMenu, I saw your modpack and toke some assets and forget to add in credits so sorry about that, and I understand you, I will remove them as fast as I can and about the differences, my modpack focuses to port the vanilla bedrock into java without adding extra features and I was only gonna do the Title Screen and thank you for the inspiration, i appericate it and will remove them!

- Wish you a nice day 🙏

**Comment by seriousfreezing** [comment]
Currently the icons that are allowed and that are mine are:
- All from the “fancymenu/assets/bg” folder except the Marketplace banner (i.e. bt_market and bt_market_hover are not allowed to be used).
- Loading.gif, Minecraft.png, Resource.png, Lan.png, Close.png/Down.png and their variations (currently not in the modpack, will be in an update, but these can be used).

**Comment by seriousfreezing** [comment]
> Also tbh, when me and SoftwareDevKit was doing the first version, we didn't even know about your modpack, after I finished the first version and added FancyMenu, I saw your modpack and toke some assets and forget to add in credits so sorry about that, and I understand you, I will remove them as fast as I can and about the differences, my modpack focuses to port the vanilla bedrock into java without adding extra features and I was only gonna do the Title Screen and thank you for the inspiration, i appericate it and will remove them!
> 
>     * Wish you a nice day 🙏

Relax, I hope your modpack is successful and I even recommend that you take the interfaces I made because it takes a lot of work to redo from scratch, something similar.

**Comment by Tminec** [comment]
> Thanks, I'll be waiting for you to remove the artwork from the fancymenu/assets/icons folder. You can use the other artwork as you like, as it's not by the same artist.

I am removing the things now but I didn't borrow the ones from the `config\fancymenu\assets\icon` folder

**Comment by Tminec** [comment]
I credited the assets and working for the new version without the assets (expect the ones you allowed me to use) it will be a bit hard for the marketplace.gif so I hope I can make the update this month!

**Comment by seriousfreezing** [comment]
No rush for masterpieces! I recommend you read [the article](https://github.com/seriousfreezing/BedrockReloaded/wiki/Forks) I'm developing for more tips on my modpack! :D

**Comment by Tminec** [comment]
Also, I also recommend you something, edit the `resourcify.json` and set ads to false, it will remove the server hosting ad.
And when you switch to another option in the options menu, the distant horizon button shows between the buttons.

**Comment by Tminec** [comment]
Also SoftwareDevKit's modpack doesn't include any assets from this mod and even FancyMenu so you don't have to include it in the forks.

**Comment by seriousfreezing** [comment]
> Also SoftwareDevKit's modpack doesn't include any assets from this mod and even FancyMenu so you don't have to include it in the forks.

True, I will remove it from the list. I got confused with another modpack that used my loading.gif, but unfortunately I have no way of contacting it

**Comment by seriousfreezing** [comment]
> Also, I also recommend you something, edit the `resourcify.json` and set ads to false, it will remove the server hosting ad. And when you switch to another option in the options menu, the distant horizon button shows between the buttons.

I saw this option for a moment, I'll leave it on. But in the case of the distant horizons button, I didn't understand what you said about.

**Comment by Tminec** [comment]
> > Also SoftwareDevKit's modpack doesn't include any assets from this mod and even FancyMenu so you don't have to include it in the forks.
> True, I will remove it from the list. I got confused with another modpack that used my loading.gif, but unfortunately I have no way of contacting it

Not leaving a way to contact someone about your modpack is a serious problem, I hope you can contact to him somehow.

**Comment by Tminec** [comment]
> > Also, I also recommend you something, edit the `resourcify.json` and set ads to false, it will remove the server hosting ad. And when you switch to another option in the options menu, the distant horizon button shows between the buttons.
> 
> I saw this option for a moment, I'll leave it on. But in the case of the distant horizons button, I didn't understand what you said about.

I will try to take an ss

**Comment by Tminec** [comment]
![resim](https://github.com/user-attachments/assets/da623b1d-8836-4644-83a1-a07129810241)
Here

**Comment by seriousfreezing** [comment]
> > > Also SoftwareDevKit's modpack doesn't include any assets from this mod and even FancyMenu so you don't have to include it in the forks.
> > > True, I will remove it from the list. I got confused with another modpack that used my loading.gif, but unfortunately I have no way of contacting it
> 
> Not leaving a way to contact someone about your modpack is a serious problem, I hope you can contact to him somehow.

I hate it and there's nothing I can do about it :(

**Comment by seriousfreezing** [comment]
> ![resim](https://private-user-images.githubusercontent.com/109427414/392097207-da623b1d-8836-4644-83a1-a07129810241.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNTIwNDAsIm5iZiI6MTczMzI1MTc0MCwicGF0aCI6Ii8xMDk0Mjc0MTQvMzkyMDk3MjA3LWRhNjIzYjFkLTg4MzYtNDY0NC04M2ExLWEwNzEyOTgxMDI0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QxODQ5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTgyZTQ5MDBiMGU4ODcxNGVlMWEzMzJmMGIzZTQ4M2NlNmU4MjZiMGU3NTRhMGVjYWY0YTVhZDYyMDYyODllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.sHmawUa0xi_wb46JKMRyN0-GzesA8m_ePke-jJscAsI) Here is it, I think you can simply remove it with FancyMenu and it shouldn't cause a problem.

In my update that I've been doing for almost a month, I've already fixed it using a custom button that mimics this button, i.e. fixed.

**Comment by seriousfreezing** [comment]
I spoke to the artist and her artwork is on this license, that is, it means that she allows the use of her art in her modpack but without other types of use, with clear credits.
More details: https://www.tldrlegal.com/license/creative-commons-attribution-noncommercial-noderivs-cc-nc-nd

The way she asks you to put the credits is just like that in your modpack description:
[Mp3Rosa](https://www.instagram.com/_mp3rosa_/)

Then you put yourself as the artist of some assets or something.
Yes, this applies to the other assets listed in my article, I'm still going to update this article but I'm too lazy.
